# k8s/01-secrets.yaml
# Tất cả Secrets cho project - sử dụng credentials thật từ .env
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: crypto-analytics
type: Opaque
stringData:
  root-username: root
  root-password: changeme
  uri: "mongodb://root:changeme@mongodb:27017"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: crypto-analytics
type: Opaque
stringData:
  root-user: admin
  root-password: password
  access-key: admin
  secret-key: password
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
  namespace: crypto-analytics
type: Opaque
stringData:
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
  SMTP_USER: luudungpkt922005@gmail.com
  SMTP_PASSWORD: "fthg cyol auel zprl"
  EMAIL_FROM: luudungpkt922005@gmail.com
---
apiVersion: v1
kind: Secret
metadata:
  name: binance-credentials
  namespace: crypto-analytics
type: Opaque
stringData:
  api-key: ZA1o5H2XNLl3gSJiTDx0S08nYKOW6RPpYbiASSR02U79dDA5NHVDHzXitMKtdU0q
  api-secret: F69oAvMLIlLeRSoD4TKuqiXMTyq9YdJyl5hspIhoszu75MypdeAQ9SWf7uy1gzyK
